apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-argo
  template:
    metadata:
      labels:
        app: hello-argo
    spec:
      containers:
      - name: hello-argo
        image: shuraosipov/hello-argo:latest
        ports:
        - containerPort: 8080

