apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-argocd
  template:
    metadata:
      labels:
        app: hello-argocd
    spec:
      containers:
      - name: hello-argocd
        image: shuraosipov/hello-argo:latest
        ports:
        - containerPort: 8080

